#!/usr/bin/env bash
set -e

ROOT="$( cd $(dirname $0)/.. && pwd)"

repodir="/tmp/kubeflow-pipelines"

if [ ! -d ${repodir} ]; then
    git clone git@github.com:kubeflow/pipelines.git ${repodir}
fi

depsdir=${ROOT}/configure-pipeline/dependencies

rm -rf ${depsdir}/*
mkdir -p ${depsdir}

pushd ${repodir}
    git checkout 2.0.3

    kustomize build manifests/kustomize/cluster-scoped-resources/ > ${depsdir}/kubeflow.yaml

    git reset --hard origin/HEAD
popd
