#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
export name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
export size="$(yq eval '.spec.size' /kratix/input/object.yaml)"

export replicas=1

if [ $size = large ]; then
  replicas=3
fi

# Replace defaults with user provided values
cat /tmp/transfer/kafka-instance.yaml |  \
  yq eval '.spec.kafka.replicas = env(replicas)' | \
  yq eval '.metadata.name = env(name)' - \
  > /kratix/output/kafka-instance.yaml
