#!/usr/bin/env bash

set -e

root=$(cd $(dirname $0)/..; pwd)
image_name="$1"
shift
pipeline_image="ghcr.io/syntasso/kratix-marketplace/pipeline-${image_name}-image:v0.1.0"

if [ ! -d "${root}/${image_name}" ]; then
  echo "Directory ${image_name} does not exist"
  exit 1
fi

while [ $# -gt 0 ]; do
  case "$1" in
    build)
      docker build \
        --tag "${pipeline_image}" \
        --platform linux/amd64 \
        "${root}/${image_name}" ;;

    load)
      kind load docker-image "${pipeline_image}" --name platform ;;

    push)
      docker push "${pipeline_image}" ;;

    rmi)
      docker rmi --force "${pipeline_image}" ;;

    pull)
      docker pull "${pipeline_image}" ;;

    *)
      echo "unknown command $1"
      exit 1
      ;;
  esac
  shift
done
