---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: TBDNAME
  namespace: default
spec:
  version: 8.5.3
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: TBDNAME
  namespace: default
spec:
  version: 8.5.3
  count: 1
  elasticsearchRef:
    name: TBDNAME
