#!/usr/bin/env bash
set -e

ROOT="$( cd $(dirname $0)/.. && pwd)"

urls=(
    "https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml"
)


depsdir=${ROOT}/configure-pipeline/dependencies/

rm -rf ${depsdir}/*
mkdir -p ${depsdir}

for url in ${urls[@]}; do
    filename=$(basename ${url})
    curl -sL "${url}" -o ${depsdir}/${filename}
done
