#!/usr/bin/env sh

set -eu

app_name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
app_namespace="$(yq eval '.metadata.namespace // "default"' /kratix/input/object.yaml)"
pg_safe_name="$(printf '%s' "$app_name" | tr '-' '_')"

database_requested=false
database_driver="$(yq eval '.spec.database.driver // ""' /kratix/input/object.yaml)"

k8s_resource_name="${app_name}-db"     # e.g., app-stack-db (For Kubernetes)
pg_database_name="${pg_safe_name}_db"  # e.g., app_stack_db (For Postgres)

if [ "${database_driver}" = "postgresql" ]; then
  database_requested=true

  cat > /kratix/output/postgresql-request.yaml <<EOF
apiVersion: marketplace.kratix.io/v1alpha2
kind: postgresql
metadata:
  name: ${k8s_resource_name}
  namespace: ${app_namespace}
  labels:
    kratix.io/component-of-promise-name: app-stack
    kratix.io/component-of-resource-name: ${app_name}
    kratix.io/component-of-resource-namespace: ${app_namespace}
spec:
  env: dev
  teamId: ${app_name}
  dbName: ${pg_database_name}
EOF
fi

cat > /kratix/metadata/status.yaml <<EOF
message: Dependency requests created
dependencies:
  database:
    requested: ${database_requested}
    requestName: "${k8s_resource_name}"
EOF
