#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

resources_dir=$PWD/configure-pipeline/resources
mkdir -p ${resources_dir}
rm -rf ${resources_dir}/*

runtime_image="ghcr.io/syntasso/kratix-marketplace/jenkins-runtime:v0.1.0"

instance_urls=(
    'https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/v0.9.0-beta2/config/samples/jenkins.io_v1alpha2_jenkins.yaml'
)

for url in "${instance_urls[@]}"; do
    curl -sL -o ${resources_dir}/$(basename $url) $url
done

# Plugins are baked into a dedicated Jenkins runtime image. The operator is configured
# to skip plugin installation at startup and only reconcile the Jenkins resource.
yq -i '. | 
    .spec.master.containers[0].image="'${runtime_image}'" |
    .spec.master.containers[0].imagePullPolicy="IfNotPresent" |
    .spec.master.containers[0].env= [
        { "name": "DEBUG_JENKINS_OPERATOR", "value": "true"},
        { "name": "JAVA_OPTS", "value": "-Xmx2048m -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -Djenkins.install.runSetupWizard=false -Djava.awt.headless=true"}
    ] |
    .spec.master.skipPlugins=true |
    del(.spec.master.basePlugins) |
    del(.spec.master.plugins) |
    del(.spec.seedJobs)' ${resources_dir}/jenkins.io_v1alpha2_jenkins.yaml


yq '. | .metadata.name="dev-NAME"' ${resources_dir}/jenkins.io_v1alpha2_jenkins.yaml > ${resources_dir}/dev-jenkins-instance.yaml
yq '. | .metadata.name="prod-NAME"' ${resources_dir}/jenkins.io_v1alpha2_jenkins.yaml > ${resources_dir}/prod-jenkins-instance.yaml
rm ${resources_dir}/jenkins.io_v1alpha2_jenkins.yaml
