#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"
mkdir -p ${PWD}/configure-pipeline/dependencies

urls=(
  'https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/v0.9.0-beta2/config/crd/bases/jenkins.io_jenkins.yaml'
  'https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/v0.9.0-beta2/deploy/all-in-one-v1alpha2.yaml'
)

for url in "${urls[@]}"; do
    curl -sL -o ${PWD}/configure-pipeline/dependencies/$(basename $url) $url
done
