#!/usr/bin/env bash

set -euo pipefail

PWD="$( cd "$(dirname "$0")/.." && pwd )"
image_dir="${PWD}/jenkins-runtime-image"
version="v0.1.0"
image_name="${JENKINS_RUNTIME_IMAGE:-ghcr.io/syntasso/kratix-marketplace/jenkins-runtime:${version}}"
platform="${BUILD_PLATFORM:-linux/arm64,linux/amd64}"

declare -a args=( "$@" )
if ! [ -d "${image_dir}" ]; then
  echo "missing image directory: ${image_dir}"
  exit 1
fi

while [ $# -gt 0 ]; do
  case "$1" in
    build)
      docker build \
        --tag "${image_name}" \
        --platform "linux/$(uname -m)" \
        "${image_dir}"
      ;;

    load)
      kind load docker-image "${image_name}" --name platform
      ;;

    push)
      if ! docker buildx ls | grep -q "kratix-image-builder"; then
        docker buildx create --name kratix-image-builder
      fi
      docker buildx build \
        --builder kratix-image-builder \
        --tag "${image_name}" \
        --platform "${platform}" \
        --push \
        "${image_dir}"
      ;;

    pull)
      docker pull "${image_name}"
      ;;

    rmi)
      docker rmi --force "${image_name}"
      ;;

    *)
      echo "unknown command $1"
      exit 1
      ;;
  esac
  shift
done
