#!/usr/bin/env sh

set -xeo pipefail


function main() {
    export TEAM="$(yq eval '.spec.team' /kratix/input/object.yaml)"
    export K8S_ADDR="$(yq eval '.spec.kubernetes.host' /kratix/input/object.yaml)"
    yq eval '.spec.kubernetes.caCert' /kratix/input/object.yaml > ca.cert
    export VAULT_NAMESPACE="$(kubectl -n default get configmap vault -o jsonpath='{.data.parentNamespace}')"
    export VAULT_ADDR="$(kubectl -n default get configmap vault -o jsonpath='{.data.url}')"
    export AUTHPATH="$(kubectl -n default get configmap vault -o jsonpath='{.data.authpath}')"

    verify_vault_connection

    login_to_vault

    create_namespace_with_kv_engine

    enable_kubernetes_auth

    update_status
}

function verify_vault_connection() {
    echo "Verifying that vault is reachable"
    vault status
}


function login_to_vault() {
    echo "logging into vault"
    role="$(kubectl -n default get configmap vault -o jsonpath='{.data.role}')"
    jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)

    vault login $(vault write --format=yaml auth/${AUTHPATH}/login role=${role} jwt="${jwt}" | yq .auth.client_token) >/dev/null
}

function create_namespace_with_kv_engine() {
    echo "Creating namespace $TEAM"
    vault namespace create "$TEAM"
    echo "---"

    export VAULT_NAMESPACE=$VAULT_NAMESPACE/$TEAM

    echo "Enabling KV v2 engine"
    vault secrets enable -version=2 kv

    echo "Creating read-only policy for the new KV engine"

    vault write sys/policy/kv-read policy=@readonly.hcl
}

function enable_kubernetes_auth() {
    echo "Enabling kubernetes auth engine"

    vault auth enable kubernetes

    vault write auth/kubernetes/config \
        kubernetes_host="${K8S_ADDR}" \
        kubernetes_ca_cert=@ca.cert

    vault write auth/kubernetes/role/kv-read \
        bound_service_account_names="*" \
        bound_service_account_namespaces="${TEAM}" \
        policies=kv-read \
        ttl=1h
}

function update_status() {
cat > /kratix/metadata/status.yaml <<EOF
message: namespace ${VAULT_NAMESPACE} created. All service accounts in $TEAM k8s namespace have read access to the 'kv' engine. Ensure your service accounts have the system:auth-delegator clusterrole bound.
EOF
}

main
