#!/usr/bin/env sh

set -x

username="$(yq eval '.spec.username' /input/object.yaml | tr '[:upper:]' '[:lower:]')"
sed "s/TBDNAME/${username}/g" /tmp/transfer/token-generator-job.yaml > /output/token-generator-job.yaml
