#!/usr/bin/env bash

set -euo pipefail

ls -l /kratix/output

cat /kratix/output/*

if yq --exit-status 'select(.kind == "Secret")' /kratix/output/* >/dev/null; then
    echo "found secrets output"
    exit 1
fi

if ! yq --exit-status 'select(.kind == "ConfigMap")' /kratix/output/* >/dev/null; then
    echo "didnt find the expected configmap in output"
    exit 1
fi

if ! yq --exit-status 'select(.kind == "SealedSecret")' /kratix/output/* >/dev/null; then
    echo "didnt find the expected sealedsecret in output"
    exit 1
fi

echo "all documents accounted for!!"
