#!/usr/bin/env bash

kubectl apply -f ../namespace/promise.yaml
../namespace/internal/scripts/pipeline-image build load

kubectl wait --for=condition=Established crd/namespaces.marketplace.kratix.io --timeout=100s