#!/usr/bin/env sh

set -ex

name="$(yq eval '.metadata.name' /input/object.yaml)"

sed "s/TBDNAME/${name}/g" /tmp/transfer/elasticsearch.yaml > /output/elasticsearch.yaml
sed "s/TBDNAME/${name}/g" /tmp/transfer/kibana.yaml > /output/kibana.yaml