#!/usr/bin/env sh

set -xe

export VAULT_ADDR="$(kubectl get configmap vault-pipeline-image -o jsonpath='{.data.url}')"
export AUTHPATH="$(kubectl get configmap vault-pipeline-image -o jsonpath='{.data.authpath}')"

echo "logging into vault"
role="$(kubectl get configmap vault-pipeline-image -o jsonpath='{.data.role}')"
jwt=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
token=$(vault write --format=yaml auth/${AUTHPATH}/login role=${role} jwt="${jwt}" | yq .auth.client_token)

vault login ${token} >/dev/null

echo "verifying vault is accessible"
vault status

kubectl create secret generic supersecret \
    --from-literal=accesskey=superkey \
    --from-literal=secretkey=supersecret \
    --dry-run=client -o yaml > /kratix/output/secrets.yaml
echo -e "\n---\n" >> /kratix/output/secrets.yaml
kubectl create secret generic topsecret \
    --from-literal=private=value \
    --from-literal=password=secr3t \
    --dry-run=client -o yaml >> /kratix/output/secrets.yaml

kubectl create deployment nginx --image=nginx --dry-run=client -o yaml > /kratix/output/deployment.yaml

cat > /kratix/input/object.yaml <<EOF
apiVersion: v1
kind: ResourceRequest
metadata:
  name: myresource
  namespace: default
EOF
