apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  labels:
    kratix.io/promise-version: v0.1.0
  name: tekton
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      creationTimestamp: null
      name: tekton.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: tekton
        plural: tekton
        singular: tekton
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  dashboard:
                    properties:
                      enabled:
                        type: boolean
                      ingress:
                        properties:
                          url:
                            type: string
                        type: object
                      mode:
                        default: read-only
                        description: 'Access mode to the resources: read-only or read-write'
                        type: string
                    type: object
                  version:
                    type: string
                type: object
            type: object
        served: true
        storage: true
    status:
      acceptedNames:
        kind: ""
        plural: ""
      conditions: null
      storedVersions: null
  workflows:
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: tekton-package
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/tekton-configure-pipeline:v0.1.0
            name: create-instance
status: {}
