#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
env_type="$(yq eval '.spec.env // "dev"' /input/object.yaml)"

cp /tmp/transfer/*.yaml /output

# This statement is designed to represent a difference in deployment complexity 
# in a dev vs prod environment. In the case of Knative we switch autoscaling 
# on in production, we switch it off in dev. 
if [ "${env_type}" = "dev" ];
then
  rm /output/serving-hpa.yaml
fi
