#!/usr/bin/env bash

set -e

test_promise() {
  kubectl wait promise/runtime --for=condition=ConfigureWorkflowCompleted --timeout=120s
  kubectl wait --for=condition=Available --timeout=5s deployment/nginx-nginx-ingress-controller
}

test_resource_request() {
  kubectl wait --for=condition=Available --timeout=5s deployment/example-runtime
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
