#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

rdir="$PWD/request-pipeline/resources/"
rm -rf "${rdir}"
mkdir -p "${rdir}"

cat > "${rdir}/prod-rabbitmq-instance.yaml" <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: TBDNAME
  namespace: TBDNAMESPACE
spec:
    replicas: 3
    rabbitmq:
      additionalPlugins: []
EOF

cat > "${rdir}/dev-rabbitmq-instance.yaml" <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: TBDNAME
  namespace: TBDNAMESPACE
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins: []
    additionalConfig: |
      log.console.level = debug
EOF
