#!/usr/bin/env sh

set -x

# Add logic for pipeline here.
# Example:
# name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
# sed "s/TBDNAME/${name}/g" /tmp/transfer/filename.yaml > /kratix/output/filename.yaml
