#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"
mkdir -p ${PWD}/resources

output_file=${PWD}/resources/nginx-controller-operator.yaml
touch ${output_file}

kubectl kustomize \
    'https://github.com/nginxinc/nginx-ingress-helm-operator/config/default?ref=v1.2.1' \
    --output ${output_file}
