#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"
mkdir -p ${PWD}/resources

DIR=$(mktemp -d)
echo """---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 'https://github.com/nginxinc/nginx-ingress-helm-operator/config/default?ref=v1.2.1'
  - 'https://github.com/nginxinc/nginx-ingress-helm-operator/config/samples?ref=v1.2.1'

patches:
  - target:
      group: charts.nginx.org
      version: v1alpha1
      kind: NginxIngress
      name: nginxingress-sample
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: default
""" > $DIR/kustomization.yaml

kubectl kustomize $DIR --output $PWD/resources/operator-and-basic-install.yaml
