#!/usr/bin/env bash
set -e

test_promise() {
  kubectl --context kind-platform apply -f https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/app-stack/promises/runtime-release.yaml
  kubectl --context kind-platform apply -f https://raw.githubusercontent.com/syntasso/kratix-marketplace/main/app-stack/promises/postgres-release.yaml
  kubectl --context kind-worker wait --for=condition=Available --namespace default deployment/postgres-operator
  kubectl --context kind-platform get crd appstacks.marketplace.kratix.io
}

test_resource_request() {
  kubectl describe appstack my-app-stack | grep -F "Suspended"
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
