#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
env_type="$(yq eval '.spec.env // "dev"' /input/object.yaml)"
name="$(yq eval '.metadata.name' /input/object.yaml)"

sed "s/NAMETBD/${name}/g" /tmp/transfer/vault.yaml > /output/vault.yaml

# This statement is designed to represent a difference in deployment complexity 
# in a dev vs prod environment. In the case of Vault we unseal our dev instance, 
# we leave prod sealed.
if [ "${env_type}" = "dev" ];
then
  sed "s/NAMETBD/${name}/g" /tmp/transfer/unseal.yaml > /output/unseal.yaml
fi