#!/usr/bin/env sh

set -eux

if [ "$KRATIX_WORKFLOW_TYPE" = "resource" ]; then
  # Read current values from the provided resource request
  export name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
  export size="$(yq eval '.spec.size' /kratix/input/object.yaml)"

  # default small size
  export replicas=1

  if [ $size = large ]; then
    replicas=3
  fi

  # Replace defaults with user provided values
  cat /tmp/transfer/redis-instance.yaml |  \
    yq eval '.metadata.name = env(name)' | \
    yq eval '.spec.redis.replicas = env(replicas)' | \
    yq eval '.spec.sentinel.replicas = env(replicas)' - \
    > /kratix/output/redis-instance.yaml
  exit 0
fi

if [ "$KRATIX_WORKFLOW_TYPE" = "promise" ]; then
  cp -r /tmp/transfer/dependencies/* /kratix/output/
  exit 0
fi

echo "unsupported KRATIX_WORKFLOW_TYPE: $KRATIX_WORKFLOW_TYPE"
exit 1
