#!/usr/bin/env bash

set -euo pipefail

if [ -f /kratix/metadata/auto-approve ]; then
  echo "Auto-approve enabled. Skipping issue creation..."
  exit 0
fi

currentRequest=$(yq -r '.status.approvalIssue' /kratix/input/object.yaml)
if [ "$currentRequest" != "null" ]; then
  echo "Approval issue already exists (or auto-approved). Skipping issue creation..."
  exit 0
fi

echo "New $(yq -r '.kind' /kratix/input/object.yaml) requested"
echo "" >> issue-body
echo "Close the issue to accept; Close it as not-planned to reject" >> issue-body
echo "" >> issue-bod
echo '```yaml' >> issue-body
cat /kratix/input/object.yaml | yq 'del(.status)' >> issue-body
echo '```' >> issue-body

issue=$(gh issue create \
  --repo $GITHUB_REPOSITORY \
  --title "New $(yq -r '.kind' /kratix/input/object.yaml) request waiting approval" \
  --body-file issue-body)

echo "approvalIssue: $(echo $issue)" > /kratix/metadata/status.yaml
echo "message: Waiting approval. Check $(echo $issue) for details" >> /kratix/metadata/status.yaml
