apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: dex-group-authentication
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: dex-group-authentications.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: dex-group-authentication
        plural: dex-group-authentications
        singular: dex-group-authentication
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  clusterRole:
                    default: view
                    description: An existing ClusterRole to bind the group to.
                    type: string
                  userGroup:
                    description: The user group to provide access to.
                    type: string
                type: object
            type: object
        served: true
        storage: true
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-config
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/dex-group-authentication-configure-pipeline:v0.1.0
            name: dex-group-auth-config-pipeline
            command: [ promise-configure ]
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-config
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/dex-group-authentication-configure-pipeline:v0.1.0
            name: dex-group-auth-config-pipeline
            command: [ resource-configure ]
status: {}
