apiVersion: marketplace.kratix.io/v1alpha2
kind: postgresql
metadata:
  name: example
  namespace: default
spec:
  env: dev
  namespace: default
  teamId: acid
  dbName: bestdb
  vault:
    enabled: true
    appServiceAccount: example-app-sa
    appServiceAccountNamespace: default
    kubernetesAuthPath: kubernetes
