#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

mkdir -p $PWD/request-pipeline/resources

cat > $PWD/request-pipeline/resources/baseline-resources.yaml <<EOF
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: TBDNAME
  namespace: default
spec:
  version: 8.5.3
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: TBDNAME
  namespace: default
spec:
  version: 8.5.3
  count: 1
  elasticsearchRef:
    name: TBDNAME
---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: TBDNAME
  namespace: default
spec:
  type: filebeat
  version: 8.5.3
  elasticsearchRef:
    name: TBDNAME
  config:
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
  daemonSet:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
EOF

cat > $PWD/request-pipeline/resources/autoscaling.yaml <<EOF
---
apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: TBDNAME
  namespace: default
spec:
  elasticsearchRef:
    name: TBDNAME
  policies:
    - name: data-ingest
      roles: ["data", "ingest" , "transform"]
      resources:
        nodeCount: {min: 1, max: 3}
        cpu: {min: 1, max: 2}
        memory: {min: 2Gi, max: 3Gi}
        storage: {min: 1Gi, max: 5Gi}
    - name: ml
      roles:
        - ml
      resources:
        nodeCount: {min: 1, max: 3}
        cpu: {min: 1, max: 2}
        memory: {min: 2Gi, max: 3Gi}
        storage: {min: 1Gi, max: 5Gi}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: TBDNAME
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: kibana.k8s.elastic.co/v1
    kind: Kibana
    name: TBDNAME
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
EOF