#!/usr/bin/env bash
set -e

test_promise() {
  # vault has no WCR
  kubectl get crd vaults.marketplace.kratix.io
}

test_resource_request() {
  kubectl wait --for=condition=ready --timeout=5s pod/vault-0
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
