#!/usr/bin/env bash
set -e

test_promise() {
  kubectl get crd prometheuses.monitoring.coreos.com
  kubectl wait --for=condition=available --timeout=5s deployment/prometheus-operator
}

test_resource_request() {
  kubectl -n monitoring wait --for=condition=available --timeout=5s prometheuses.monitoring.coreos.com k8s
  kubectl -n monitoring wait --for=condition=available --timeout=5s deployment/grafana
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
