apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  creationTimestamp: null
  name: redis-multi-cluster-replication
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: redismulticlusterreplications.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: RedisMultiClusterReplication
        plural: redismulticlusterreplications
        singular: redismulticlusterreplication
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                type: object
            type: object
        served: true
        storage: true
  workflows:
    promise: {}
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance
        spec:
          containers:
          - image: ghcr.io/syntasso/kratix-marketplace/redis-multi-cluster-replication-configure-pipeline:v0.1.0
            name: configure-redis
status: {}
