#!/usr/bin/env sh

set -eux

if [ "$KRATIX_WORKFLOW_TYPE" = "resource" ]; then
    # Read current values from the provided resource request
    name="kf-$(yq eval '.metadata.name' /kratix/input/object.yaml)"
    sed "s/TBDNAMESPACE/${name}/g" /tmp/transfer/manifest.yaml > /kratix/output/manifest.yaml
    sed "s/TBDNAMESPACE/${name}/g" /tmp/transfer/namespace.yaml > /kratix/output/namespace.yaml
else
    cp /tmp/dependencies/* /kratix/output/
fi
