#!/usr/bin/env bash

set -euxo pipefail

export name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
export size="$(yq eval '.spec.size' /kratix/input/object.yaml)"

# default small size
export tier="db-f1-micro"

if [ $size = large ]; then
  tier="db-n1-standard-8"
fi

export PROJECT_ID=$(cat /creds/project_id)
gcloud auth activate-service-account --key-file=/creds/credentials.json
gcloud config set project $PROJECT_ID

if [ "$KRATIX_WORKFLOW_ACTION" = "delete" ]; then
  set +e
  gcloud sql instances describe $name
  exitCode=$?
  set -e
  if [ $exitCode -ne 0 ]; then
    echo "Instance $name does not exist"
    exit 0
  fi
  gcloud sql instances delete $name --quiet
  exit 0
fi


set +e
gcloud sql instances describe $name
exitCode=$?
set -e
if [ $exitCode -e 0 ]; then
  echo "Instance $name already exists"
  exit 0
fi

gcloud sql instances create $name --database-version=MYSQL_8_0 --region=us-central --tier=db-f1-micro


cat <<EOF > /kratix/metadata/status.yaml
instanceStatus: available
EOF
