apiVersion: platform.kratix.io/v1alpha1
kind: PromiseRelease
metadata:
  name: postgresql
spec:
  version: v1.0.0-beta.4
  sourceRef:
    type: http
    url: https://raw.githubusercontent.com/syntasso/promise-postgresql/jm/secret-management/promise.yaml
