#!/usr/bin/env bash
set -e

test_promise() {
  kubectl wait --for=condition=Available deployment/kubevela-vela-core --timeout=5s -n vela-system
}

test_resource_request() {
  echo "no resource request"
  exit 0
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
