#!/usr/bin/env bash
set -e

test_promise() {
  kubectl get crd tekton.marketplace.kratix.io
}

test_resource_request() {
  kubectl -n tekton-pipelines wait --for=condition=Available --timeout=5s deployment/tekton-dashboard
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
