#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
export name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"

export plugins="$(yq eval '.spec.plugins // []' /kratix/input/object.yaml)"
export nodeport_override="$(yq eval '.metadata.labels.nodeport-override // ""' /kratix/input/object.yaml)"
env_type="$(yq eval '.spec.env // "dev"' /kratix/input/object.yaml)"
base_instance="/tmp/transfer/${env_type}-jenkins-instance.yaml"

if [ "${env_type}" = "dev" ]; then
  # derive a nodePort from the name
  nodePort="$(echo "${name}" | md5sum | grep -Eo "[[:digit:]]{3}" | head -n1)"
  nodePort=$(( 30000 + nodePort ))
fi

if [ "${nodeport_override}" != "" ]; then
  nodePort=${nodeport_override}
fi

# Replace defaults with user provided values
export nodePort
yq eval '.spec.master.plugins = env(plugins)' ${base_instance} |
  yq eval '.spec.service.nodePort = env(nodePort)' |
  sed "s/NAME/${name}/g" > /kratix/output/jenkins-instance.yaml
