#!/usr/bin/env bash

set -eu
exec 3>&1 1>&2

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"

workflow=$(curl -sL https://circleci.com/api/v2/insights/gh%2Fsyntasso%2Fkratix-marketplace//workflows/promises | jq -r '[.items[] | select(.status == "success")][0] | .id')
pipeline=$(curl -sL https://circleci.com/api/v2/workflow/$workflow | jq -r '.pipeline_id')

export LAST_GREEN_SHA=$(curl -sL https://circleci.com/api/v2/pipeline/fd05bc39-535c-4c32-b3f3-e9876a458295 | jq -r '.vcs.revision')
export UNTESTED_SHAS=$(git log --format=format:%H $LAST_GREEN_SHA~0..HEAD --full-diff)

promises() {
    local all_dirs=$(find $ROOT -maxdepth 1 -type d)

    declare -a arr
    for dir in $all_dirs; do
        if [ -f $dir/promise.yaml ]; then
            arr+=($dir)
        fi
    done
    echo "${arr[@]}"
}

untested_changes() {
    local dir=$1
    last_sha_for_dir=$(git log -1 --format=format:%H --full-diff $dir)
    [[ "$UNTESTED_SHAS" =~ "$last_sha_for_dir" ]]
}

pushd $ROOT
trap popd EXIT

template=/tmp/promise_to_test.yaml
cp ".circleci/scripts/promise_to_test_template.yaml" $template

target_config=.circleci/promises_to_test.yaml

test_all=false

for dir in ".circleci scripts"; do
    if untested_changes $dir; then
        test_all=true
    fi
done

for promise in $(promises); do
    if  $test_all || untested_changes $promise ; then
        name="$(basename $promise)"
        if [ "${name:0:1}" = "." ]; then
            continue
        fi
        yq ".workflows.promises.jobs[0].test-and-push.matrix.parameters.promise += [\"$name\"]" $template > $template.upd
        mv $template.upd $template
    fi
done

cat ${template} >&3
