#!/bin/sh

set -x

# Read current values from the provided resource request
export NAME=$(yq eval '.metadata.name' /input/object.yaml)
export REPO_URL=$(yq eval '.spec.source.repoURL' /input/object.yaml)
export REVISION=$(yq eval '.spec.source.revision // "HEAD"' /input/object.yaml)
export REPO_PATH=$(yq eval '.spec.source.path // "."' /input/object.yaml)

yq eval '.metadata.name = env(NAME) |
          .spec.source.repoURL = env(REPO_URL) |
          .spec.source.targetRevision = env(REVISION) |
          .spec.source.path = env(REPO_PATH)' /tmp/transfer/application.yaml  > /output/application.yaml
