#!/usr/bin/env bash
set -e

test_promise() {
  # vault has no dependencies
  exit 0
}

test_resource_request() {
  exit 0
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
