#!/usr/bin/env sh

set -x

namespace="default"

# Read current values from the provided resource request
name="$(yq eval '.metadata.name' /input/object.yaml)"
env_type="$(yq eval '.spec.env // "dev"' /input/object.yaml)"

base_instance="/tmp/transfer/${env_type}-rabbitmq-instance.yaml"

export plugins="$(yq eval '.spec.plugins // []' /input/object.yaml)"

# Replace defaults with user provided values
yq eval '.spec.rabbitmq.additionalPlugins = env(plugins)' ${base_instance} |
  sed "s/TBDNAMESPACE/${namespace}/g" |
  sed "s/TBDNAME/${name}/g" > /output/instance.yaml
