#!/usr/bin/env ruby

require 'yaml'
promise = YAML.load(ARGF.read)

wcr = promise.dig("spec", "workerClusterResources")
promise['spec'].delete("workerClusterResources")
promise['spec']['workerClusterResources'] = wcr

promise['metadata'].delete('creationTimestamp')
promise.delete('status')
puts promise.to_yaml
