#!/usr/bin/env bash

set -e

promise_name="$(basename "$(dirname "${PWD}")")"
scripts_dir="${PWD}/../../scripts"

if ! which worker-resource-builder >/dev/null; then
	echo "worker-resource-builder not installed"
	exit 1
fi

if [ ! -d "${PWD}/resources" ]; then
  exit 0
fi

promise_contents=$(worker-resource-builder \
  -k8s-resources-directory "${PWD}/resources" \
	-promise "${PWD}/../promise.yaml")

echo "$promise_contents" | ${scripts_dir}/format-promise > "${PWD}/../promise.yaml"
