#!/usr/bin/env bash

set -e

promise_name="$(basename "$(dirname "${PWD}")")"
if [ "${PROMISE_NAME:-""}" != "" ]; then
  promise_name="${PROMISE_NAME}"
fi
pipeline_dir="configure-pipeline"
if [ "${PIPELINE_DIR:-""}" != "" ]; then
  pipeline_dir="${PIPELINE_DIR}"
fi
pipeline_image="ghcr.io/syntasso/kratix-marketplace/${promise_name}-configure-pipeline:v0.1.0"

while [ $# -gt 0 ]; do
  case "$1" in
    build)
      docker build \
        --tag "${pipeline_image}" \
        --platform linux/amd64 \
        "${PWD}/${pipeline_dir}" ;;

    load)
      kind load docker-image "${pipeline_image}" --name platform ;;

    push)
      docker push "${pipeline_image}" ;;

    rmi)
      docker rmi --force "${pipeline_image}" ;;

    pull)
      docker pull "${pipeline_image}" ;;

    *)
      echo "unknown command $1"
      exit 1
      ;;
  esac
  shift
done
