#!/usr/bin/env bash

set -ex


declare -a args=( "$@" )
for dir_name in configure-pipeline configure-promise-pipeline; do
  promise_name="$(basename "$(dirname "${PWD}")")"
  if [ "${PROMISE_NAME:-""}" != "" ]; then
    promise_name="${PROMISE_NAME}"
  fi
  pipeline_dir=${dir_name}
  if [ "${PIPELINE_DIR:-""}" != "" ]; then
    pipeline_dir="${PIPELINE_DIR}"
  fi
  pipeline_image="ghcr.io/syntasso/kratix-marketplace/${promise_name}-${dir_name}:v0.1.0"

  set -- "${args[@]}"
  while [ $# -gt 0 ]; do
    case "$1" in
      build)
        docker build \
          --tag "${pipeline_image}" \
          --platform linux/amd64 \
          "${PWD}/${pipeline_dir}" ;;

      load)
        kind load docker-image "${pipeline_image}" --name platform ;;

      push)
        docker push "${pipeline_image}" ;;

      rmi)
        docker rmi --force "${pipeline_image}" ;;

      pull)
        docker pull "${pipeline_image}" ;;

      *)
        echo "unknown command $1"
        exit 1
        ;;
    esac
    shift
  done
done
