#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

urls=(
    # TODO: set URLs to download resources. Ideally use pinned version URLs.
)

for url in "${urls[@]}"; do
    curl -sL -o $PWD/resources/$(basename $url) $url
done