#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

mkdir -p $PWD/request-pipeline/resources

urls=(
    # TODO: set URLs to download resources. Ideally use pinned version URLs.
)

for url in "${instance_urls[@]}"; do
    curl -sL -o $PWD/request-pipeline/resources/$(basename $url) $url
done