#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"
resources_path=${PWD}/dependencies
mkdir -p ${resources_path}

urls=(
    # TODO: set URLs to download resources. Ideally use pinned version URLs.
)

for url in "${urls[@]}"; do
    curl -sL -o ${resources_path}/$(basename $url) $url
done
