#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

mkdir -p $PWD/request-pipeline/resources
resources_path=$PWD/request-pipeline/resources

cat > ${resources_path}/token-generator-job.yaml <<EOF
---
apiVersion: batch/v1
kind: Job
metadata:
  name: TBDNAME-token-generator
  namespace: waypoint
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: TBDNAME-token-generator
    spec:
      serviceAccountName: waypoint-token-generator
      restartPolicy: OnFailure
      containers:
        - name: token-generator
          image: ghcr.io/syntasso/kratix-marketplace/waypoint-token-generator:v1
          imagePullPolicy: IfNotPresent
          command: ["generate-token", "--username TBDNAME"]
EOF
