#!/usr/bin/env bash
set -e

test_promise() {
  kubectl wait --for=condition=ready --timeout=5s --namespace waypoint pod/waypoint-server-0
}

test_resource_request() {
  # kubectl get secrets --namespace waypoint annedeveloper-token-generator
  echo "Not currently testable without loadbalancer in CI"
  exit 0
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
