#!/usr/bin/env sh

set -xe

kubectl run nginx --image nginx --dry-run=client -o yaml > /kratix/output/nginx.yaml
kubectl run mongo --image mongo:5.0.6 --dry-run=client -o yaml > /kratix/output/mongo.yaml
kubectl create deployment kratix --image syntassodev/kratix-platform:2d4792c46094ffb7ce92a58c148c9ee3cc5499ab --dry-run=client -o yaml > /kratix/output/kratix-deployment.yaml
