#!/usr/bin/env sh

set -eux

if [ "$KRATIX_WORKFLOW_TYPE" = "promise" ]; then
  cp -r /tmp/transfer/dependencies/* /kratix/output/
  exit 0
fi

echo "unsupported KRATIX_WORKFLOW_TYPE: $KRATIX_WORKFLOW_TYPE"
exit 1
