#!/usr/bin/env sh

set -x

# Read current values from the provided resource request
name="kf-$(yq eval '.metadata.name' /input/object.yaml)"


sed "s/TBDNAMESPACE/${name}/g" /tmp/transfer/manifest.yaml > /output/manifest.yaml
sed "s/TBDNAMESPACE/${name}/g" /tmp/transfer/namespace.yaml > /output/namespace.yaml

