#!/usr/bin/env bash
set -e

test_promise() {
  kubectl get crd apps.marketplace.kratix.io
}

test_resource_request() {
  exit 0
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
