#!/usr/bin/env bash
set -e

test_promise() {
  kubectl get crd app.marketplace.kratix.io
  kubectl wait --for=condition=Available --namespace default deployment/postgres-operator
}

test_resource_request() {
  exit 0
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
