#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"


helm repo add dapr https://dapr.github.io/helm-charts/
helm repo update

# helm template dapr dapr/dapr -n dapr-system --create-namespace --version 1.9.6 > $PWD/resources/helm.yaml

helm show crds dapr/dapr --version 1.10.7 > $PWD/resources/crds.yaml
DIR=$(mktemp -d)
helm template dapr/dapr --version 1.10.7 > $DIR/resources.yaml

echo """---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dapr-system

resources:
  - resources.yaml
""" > $DIR/kustomization.yaml

kubectl kustomize $DIR --output $PWD/resources/dapr.yaml

echo "This is nearly complete. Final step is to add --- to seperate crds in the internal/resources/crd.yaml file"
exit 1

