#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"
DEPENDENCIES_DIR=${PWD}/configure-pipeline/dependencies


helm repo add dapr https://dapr.github.io/helm-charts/
helm repo update

# helm template dapr dapr/dapr -n dapr-system --create-namespace --version 1.13.2 > $PWD/resources/helm.yaml

mkdir -p ${DEPENDENCIES_DIR}
helm show crds dapr/dapr --version 1.13.2 > ${DEPENDENCIES_DIR}/crds.yaml
DIR=$(mktemp -d)
helm template dapr/dapr --version 1.13.2 > $DIR/resources.yaml

echo """---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dapr-system

resources:
  - resources.yaml
""" > $DIR/kustomization.yaml

kubectl kustomize $DIR --output ${DEPENDENCIES_DIR}/dapr.yaml

echo "This is nearly complete. Final step is to add --- to seperate crds in the ${DEPENDENCIES_DIR}/crds.yaml file"
exit 1
