#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"


helm repo add dapr https://dapr.github.io/helm-charts/
helm repo update

helm template dapr dapr/dapr -n dapr-system --create-namespace --version 1.9.6 > $PWD/resources/helm.yaml

helm show crds dapr/dapr --version 1.9.6 $PWD/resources/crds.yaml

echo "The charts for dapr is broken. Two manuals steps: \n 1. Add the namespaces to the resources (see inject-wcr script for info on how to do this) \n 2. Make the crd.yaml file a valid list of yaml documents, its missing some seperators by default"
exit 1

