#!/usr/bin/env bash
set -e

test_promise() {
  kubectl wait -n dapr-system deployment/dapr-operator --for condition=Available --timeout=60s
}

test_resource_request() {
  exit 0
}

if [ "$1" = "promise" ]; then
  test_promise
else
  test_resource_request
fi
