#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

mkdir -p $PWD/request-pipeline/resources/instance

instance_urls=(
    "https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-core.yaml"
    "https://github.com/knative/net-kourier/releases/download/knative-v1.8.1/kourier.yaml"
    "https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-default-domain.yaml"
    "https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-hpa.yaml"
)

for url in "${instance_urls[@]}"; do
    curl -sL -o $PWD/request-pipeline/resources/instance/$(basename $url) $url
done