#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

urls=(
    "https://github.com/knative/serving/releases/download/knative-v1.8.3/serving-crds.yaml"
)

for url in "${urls[@]}"; do
    curl -sL -o $PWD/resources/$(basename $url) $url
done