#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"
mkdir -p ${PWD}/resources

DIR=$(mktemp -d)

cat > $DIR/config.yaml <<EOF
issuer: https://localhost:32000
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  https: 0.0.0.0:5556
  tlsCert: /etc/dex/tls/tls.crt
  tlsKey: /etc/dex/tls/tls.key
connectors:
- type: github
  id: github
  name: GitHub
  config:
    clientID: \$GITHUB_CLIENT_ID
    clientSecret: \$GITHUB_CLIENT_SECRET
    redirectURI: https://localhost:32000/callback
    loadAllGroups: true
staticClients:
- id: kube
  redirectURIs:
  - http://localhost:8000
  - http://localhost:18000
  name: kubernetes
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
EOF

cat > $DIR/kustomization.yaml <<EOF
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 'https://raw.githubusercontent.com/dexidp/dex/v2.35.3/examples/k8s/dex.yaml'

replicas:
- name: dex
  count: 2

configMapGenerator:
- name: dex
  namespace: dex
  behavior: replace
  files:
    - config.yaml
EOF

kubectl kustomize $DIR --output $PWD/resources/dex.yaml

cat > $PWD/resources/oidc-clusterrolebinding.yaml <<EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: https://localhost:32000#CgcxNTU3MzQ2EgZnaXRodWI
EOF
