#!/usr/bin/env sh

set -xe

mkdir -p /kratix/metadata/notifications

cat > /kratix/metadata/notifications/message.yml <<EOF
message: |
    :gem: :raised_hands: :rocket: :moon: :doge:
slackHook:
  secretName: slack-channel-hook
  namespace: default
EOF
