apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: dummy
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: dummy.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: dummy
        plural: dummy
        singular: dummy
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    name:
                      type: string
                  type: object
              type: object

          served: true
          storage: true
  workflows:
    promise:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: echo-hello
          spec:
            containers:
              - name: echo
                image: alpine
                command:
                  - /bin/sh
                  - -exc
                  - |
                    echo "Say Hello ..."
                    echo "A cool message" > /kratix/output/cool_message.txt
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: create-sa
          spec:
            containers:
              - name: create-sa
                image: kratix-tools:0.1.0
                command:
                  - /bin/sh
                  - -exc
                  - |
                    echo "Promise content ..."
                    cat /kratix/input/object.yaml
                    
                    echo "Got the name of the spec name field of the request"
                    REQUEST_NAME=$(cat /kratix/input/object.yaml | yq -r '.spec.name')

                    cat > /kratix/output/sa.yaml <<EOF
                    apiVersion: v1
                    kind: ServiceAccount
                    metadata:
                      name: $REQUEST_NAME
                      namespace: default
                    EOF
